server.port=9015
management.server.port=9015

#######################################
#  KAFKA 
#######################################
kafka.bootstrap-servers=localhost:29092
spring.sleuth.messaging.kafka.enabled=false
kafka.properties.security.protocol=PLAINTEXT
kafka.properties.sasl.mechanism=PLAINTEXT
kafka.properties.sasl.jaas.config=PLAINTEXT
kafka.properties.ssl.truststore.location=PLAINTEXT
kafka.properties.ssl.truststore.password=PLAINTEXT
kafka.enablessl=false
kafka.oauth.tenantId=
kafka.oauth.appId=
kafka.oauth.pfxPathName=
kafka.oauth.pwd=
#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://localhost:27888
spring.data.mongodb.database=FSE_GTW

#######################################
# Microservices url
#######################################
ms.url.gtw-config=http://localhost:8018

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console